### ISSUE TITLE
Windows10上不起作用

### ISSUE THREAD

**Issue by happyjohann** [stackia/DNSAgent#15]
![dns agent configuration](https://cloud.githubusercontent.com/assets/11272416/11166922/5023b816-8b87-11e5-807e-b130010104eb.png)
![dns not functioning](https://cloud.githubusercontent.com/assets/11272416/11166923/50241c52-8b87-11e5-8321-125ec6051470.png)
![dns setting](https://cloud.githubusercontent.com/assets/11272416/11166921/502357fe-8b87-11e5-8a65-5004fd0108f4.png)

难道是我的配置有问题？
别的软件，如Acrylic DNS Proxy也无法正常工作……

**Comment by stackia** [comment]
用 nslookup 命令查一下这两个域名，看看是不是 127.0.0.1 返回的？

**Comment by happyjohann** [comment]
![dns nslookup](https://cloud.githubusercontent.com/assets/11272416/11181675/3488ee5a-8c9f-11e5-81b6-1acae0e4d413.png)

重启后的结果，无论默认网关有没有填写，都是上图的结果。

**Comment by gdh1995** [comment]
应该是网卡优先级的问题，Win8.1是：网络和共享中心，（左边）更改适配器设置，（按Alt键来显示菜单）高级，高级设置。

里边对网卡有排序，DNS解析时只使用最上方的网卡的相应设置，除非网卡被禁用

**Comment by happyjohann** [comment]
@stackia 谢谢，确实是IPv6问题，取消选择IPv6项后，可以正常使用了
