### ISSUE TITLE
 指定了域名服务器不起作用

### ISSUE THREAD

**Issue by osssx** [stackia/DNSAgent#3]
rules.cfg文件相关内容
```
 "Pattern": "dl\\.google\\.com$",
 "NameServer": "114.114.114.114"
```
nslookup 结果：
> nslookup dl.google.com
1.0.0.127.in-addr.arpa
        primary name server = localhost
        responsible mail addr = nobody.invalid
        serial  = 1
        refresh = 600 (10 mins)
        retry   = 1200 (20 mins)
        expire  = 604800 (7 days)
        default TTL = 10800 (3 hours)
服务器:  UnKnown
Address:  127.0.0.1

>DNS request timed out.
    timeout was 2 seconds.
DNS request timed out.
    timeout was 2 seconds.
DNS request timed out.
    timeout was 2 seconds.
DNS request timed out.
    timeout was 2 seconds.
*** 请求 UnKnown 超时

指定114.114.114.114的nslookup结果：
> nslookup dl.google.com 114.114.114.114
服务器:  public1.114dns.com
Address:  114.114.114.114

>非权威应答:
名称:    dl.l.google.com
Addresses:  2404:6800:4008:c03::5b
          203.208.49.166
          203.208.49.165
          203.208.49.164
          203.208.49.167
          203.208.49.162
          203.208.49.161
          203.208.49.169
          203.208.49.174
          203.208.49.160
          203.208.49.168
          203.208.49.163
Aliases:  dl.google.com

**Comment by osssx** [comment]
是配置文件的问题解决了

**Comment by stackia** [comment]
把正确的配置在这里po一下吧，谢谢啦～

**Comment by osssx** [comment]
就是贴出来的这个，可能是和我其他配置条目冲突了，把其他的删了只留下这个就好了
