### ISSUE TITLE
Regular Expression don't work ?

### ISSUE THREAD

**Issue by Cedruyne** [stackia/DNSAgent#31]
Hi,

I tried to edit rules.cfg for match dev.example.com or dev.test.org : 
`
[
    {
        "Pattern": "^dev\.([\da-z\.-]+)\.([a-z\.]{2,6})$",
        "Address": "112.223.221.26"
    }
]
`

But does'nt works.
I've test my regex on this website : https://www.regexpal.com/, it's work.

Could u help me please ?

**Comment by stackia** [comment]
You have to escape `\` character because it's in a JSON string.
```
 { "Pattern": "^dev\\.([\\da-z\\.-]+)\\.([a-z\\.]{2,6})$", "Address": "112.223.221.26" } ]
```

**Comment by Cedruyne** [comment]
Thanks stackia, works fine !
