### ISSUE TITLE
Multiple DNS and Host as Adress

### ISSUE THREAD

**Issue by middiu** [stackia/DNSAgent#6]
Hi,
let me start saying thanks for this utility you have written, saved me a lot of time!

I have two question, not sure if they are issues of I have not configured it properly:

1) in options.cfg I'm not able to specify an array of "DefaultNameServer" for example something like this. Is it my syntax wrong or it is not supported yet?
{
    "HideOnStart": false,
    "ListenOn": "127.0.0.1:53",
    "DefaultNameServer": ["8.8.8.8","4.4.4.4","x.x.x.x"],
...
}

2) I think would be nice ( at least in my case it would be) to be able to do something like in the rules:
    {
        "Pattern": "^(.*\\.google\\.com\\.au)",
        "Address": "google.com.au" <- resolve this  and use the IP  
    },
Is it possible? is it hard to implement?

Thanks for your help

Emilio

**Comment by stackia** [comment]
1. Currently using multiple DNS server is not supported. It can only use one DNS server.
2. https://github.com/stackia/DNSAgent/releases/tag/v1.4.5771 Enjoy yourself :-)

**Comment by stackia** [comment]
e.g.
```
    {
        "Pattern": "^www\\.google\\.com\\.hk$",
        "Address": "www.google.com",
        "NameServer": "8.8.4.4"
    },
    {
        "Pattern": "^www\\.google\\.com\\.tw$",
        "Address": "www.google.com",
        "NameServer": "127.0.0.1"
    },
    {
        "Pattern": "^www\\.google\\.co\\.jp$",
        "Address": "www.google.com"
    },
    {
        "Pattern": "^www\\.google\\.com$",
        "Address": "1.2.3.4"
    }
```
www.google.com.hk will be resolved using www.google.com with name server 8.8.4.4.
www.google.com.tw will be resolved using www.google.com with DNSAgent itself.
www.google.com.co.jp will be resovled using www.google.com with default name server specified in options.cfg.

**Comment by middiu** [comment]
Amazing! it works perfectly!!!

Thanks :)
