### ISSUE TITLE
Feature request: bind on both IPv4 and IPv6 addresses

### ISSUE THREAD

**Issue by gdh1995** [stackia/DNSAgent#7]
Thanks for your work!

I want DNSAgent to bind on multi IPs, that is, one `127.0.0.0.1:53` for ipv4 protocol and the other `[::1]:53` for ipv6 protocol, and then I needn't make the second copy of DNSAgent and use two settings files.

**Comment by stackia** [comment]
Enjoy the latest release~
https://github.com/stackia/DNSAgent/releases/tag/v1.5.5776

**Comment by gdh1995** [comment]
Thanks agin! ^_^
