### ISSUE TITLE
和Windows冲突：windows默认不使用AAAA查域名

### ISSUE THREAD

**Issue by gdh1995** [stackia/DNSAgent#9]
比如，我设置了DNSAgent监听IPv4和v6的端口，里边有个
··· json
    {
        "Pattern": "^.*\\.sixxs.org$",
        "Address": "2001:1af8:4050::2",
    }
···

按现有的逻辑, DNSAgent只在发现了AAAA记录的请求时才返回Address。
但在Win8.1 x64上ping的结果如下:
```
-> 127.0.0.1 requested www.baidu.com.sixxs.org (#56830, A).
-> ::1 requested www.baidu.com.sixxs.org (#20560, A).
```

**Comment by gdh1995** [comment]
![image](https://cloud.githubusercontent.com/assets/5547703/10814331/4b89dc4c-7e60-11e5-9999-0e7f04a073e1.png)

**Comment by stackia** [comment]
这是 ping 的问题。
ping 1.2.3.4 --> 使用 IPv4 栈
ping 2404:6800:4003:c02::69 --> 使用 IPv6 栈
ping www.google.com --> 尝试解析 www.google.com 的 A 记录，然后使用 IPv4 栈
ping -6 www.google.com --> 尝试解析 www.google.com 的 AAAA 记录，然后使用 IPv6 栈

网卡里的 DNS 设置只要保留 IPv4 或者 IPv6 的一个就好。通过 IPv4 一样能向 DNS 查询 AAAA 记录。

Chrome 会检测网络是否支持 IPv6，如果支持，那么优先使用 IPv6 来连接，但是如果在 300ms 内没有接通，自动回退使用 IPv4。
http://src.chromium.org/viewvc/chrome?revision=85934&view=revision

**Comment by stackia** [comment]
要测试 DNS 解析请用 nslookup 命令。

**Comment by gdh1995** [comment]
谢, 我先去学习学习。如果可用了那我再close啊。

**Comment by gdh1995** [comment]
话说src.chromium.org的IP是哪个? 我在hosts里换了好多google的ip, 全给我报告404...

**Comment by stackia** [comment]
74.125.248.72 src.chromium.org

**Comment by gdh1995** [comment]
好吧, 看来是别的问题

![image](https://cloud.githubusercontent.com/assets/5547703/10861891/4f89d1ee-7fcd-11e5-80d2-248d958ec6c3.png)

**Comment by stackia** [comment]
![image](https://cloud.githubusercontent.com/assets/5107241/10861899/7c185e38-7fcd-11e5-8f04-be5bd568edf9.png)
帮你截个图

**Comment by gdh1995** [comment]
求解。我的设置:
* 我win8.1, 3个网卡, 第1个禁用了ipv6协议, ipv4的第一个dns是DNSAgent的
* 第2个网卡ipv4和v6都用了另外的dns server
* 第3个网卡不设ipv4的dns, ipv6的DNS设成了DNSAgent的

然后, `nslookup`的时候能看到
> 非权威应答:
> 名称:    www.baidu.com.sixxs.org
> Address:  2001:1af8:4050::2

`ping`的时候DNSAgent的ipv4端口收到A记录请求, `ping -6`却也变成了ipv4的收到Aaaa请求.

但Chrome还是上不去啊, 报告的还是 `ERR_NAME_NOT_RESOLVED`.

抱歉传图失败了好几次, 只能换文字了

**Comment by gdh1995** [comment]
补充: src.chromium.org能打开了, 谢谢

之前404应该是chrome的dns没有刷新导致的○|￣|_

**Comment by gdh1995** [comment]
另外, 我用vpn连上DNSagent在的服务器后, ipv4的dns指向dnsagent, 然后ping -6也不行了, DNSagent的l输出里就没接到请求...

**Comment by gdh1995** [comment]
问题解决，我的机子的问题应该是Windows/Chrome查询DNS的一个机制我没理解对造成的。
在“更改适配器设置”的窗口的“高级->高级设置”里可以调网卡顺序，我之前设置了Wifi > LAN，
改成LAN > Wifi就好了。

问题出在，Wifi的IPv6协议被我禁用了，只保留IPv4，LAN的都开着。然后，系统根据网卡顺序查找DNS设置，发现了Wifi网卡指定了DNSAgent做DNS server，于是就去朝DNSAgent发A记录请求，之所以不发Aaaa，是因为系统检查发现Wifi网卡禁用了IPv6，就自动不查了。

我原来以为最优先的网卡禁用IPv6的时候，系统会自动检查第二个网卡的IPv6协议配置，今天才知道竟然是直接放弃了。。。

我用修改源码的方式尝试了给A记录请求返回Aaaa记录，发现服务器上的Windows、Chrome还是认可的，可以针对性地修复我这个问题。

我已经提交了Pull Request #12，如果觉得有用你就合并吧^_^
